# Generated by Django 4.2.1 on 2023-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.CharField(max_length=100)),
                ("bot_response", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
