# Generated by Django 4.2.2 on 2023-06-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="bot_response",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="user_input",
            field=models.CharField(max_length=1000),
        ),
    ]
