# Generated by Django 4.2.2 on 2023-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_chatbot_bot_response_alter_chatbot_user_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="bot_response",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="user_input",
            field=models.CharField(max_length=100),
        ),
    ]
